galaxy_info:
  author: Javier Franco
  description: Elastic Beats for linux
  company: Datasystems

  min_ansible_version: 2.4

  platforms:
  - name: Fedora
    versions:
    - 28+
  - name: RHEL
    versions:
    - 7

  galaxy_tags:
    - web
    - system
    - monitoring
    - logging
    - elk
    - elasticsearch
