---
- name: Playbook para instalar elasticsearch
  hosts: elasticsearch
  become: true
  roles:
    - role: elk-prerequisitos

- name: Install Elasticsearch
  hosts: elasticsearch 
  become: true
  roles:
    - role: elasticsearch
      vars:
        repo_url: "http://192.168.102.224/repo/"
        rpm_name: "elasticsearch-7.15.2-x86_64.rpm"
        discovery_seed_hosts: '["192.168.102.224"]' # configurar el master tambien para esto
        elastic_master_ip: "192.168.102.224"


- name: Playbook para instalar Kibana
  hosts: kibana
  become: true
  roles:
    - role: kibana
      vars:
        repo_url: "http://192.168.102.224/repo/"
        rpm_name: "kibana-7.15.2-x86_64.rpm"
        elasticsearch_hosts: '["http://192.168.102.224:9200"]' # donde se publica el kibana 


- name: Playbook para instalar beats
  hosts: beat
  become: true
  tasks:
    - name: Install beats
      include_role:
        name: beat
      vars:
        - beat_name: "{{ item.beat_name }}"
        - rpm_name: "{{ item.rpm_name }}"
        - elastic_master_ip: 192.168.102.224
        - repo_url: "http://192.168.102.224/repo/"
      loop:
        - {rpm_name: metricbeat-7.15.2-x86_64.rpm, beat_name: metricbeat}
        - {rpm_name: filebeat-7.15.2-x86_64.rpm, beat_name: filebeat}
        - {rpm_name: packetbeat-7.15.2-x86_64.rpm, beat_name: packetbeat}
