---
- name: Copy the .deb to the server
  copy:
    src: "{{ pkg_location | default('files') }}/elasticsearch.deb"
    dest: /root/

- name: Install the elasticsearch package
  apt:
    deb: /root/elasticsearch.deb
