---
- name: Copy the rpm to the server
  copy:
    src: "/var/lib/awx/files/{{ beat_name }}.rpm"
    dest: /root/

- name: Install the elasticsearch package
  yum:
    name: /root/elasticsearch.rpm
    state: present
